name: kernel_build

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-20.04
    steps:
      - uses: manjaro-kernels/kernel-action@master
        with:
          gitlab-pw: ${{ secrets.gitlab_server_user }}
