name: Rebuild Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-20.04
    steps:
      - uses: manjaro-kernels/kernel-action@master
        with:
          gitlab-pw: ${{ secrets.gitlab_server_user }}
          build-mirror: ${{ secrets.BUILD_MIRROR }}
          branch: unstable
          bump-kernel: false
          bump-pkgrel: true
          bump-modules: repo
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          bxt-api-key: ${{ secrets.BXT_API_KEY }}
